apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
  namespace: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ngnix
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
        - image: rmkanda/ngnix-sample
          name: ngnix
          ports:
            - containerPort: 80
